<?php
/**
 * @file
 * product_features.features.field.inc
 */

/**
 * Implements hook_field_default_fields().
 */
function product_features_field_default_fields() {
  $fields = array();

  // Exported field: 'node-product_feature-body'
  $fields['node-product_feature-body'] = array(
    'field_config' => array(
      'active' => '1',
      'cardinality' => '1',
      'deleted' => '0',
      'entity_types' => array(
        0 => 'node',
      ),
      'field_name' => 'body',
      'foreign keys' => array(
        'format' => array(
          'columns' => array(
            'format' => 'format',
          ),
          'table' => 'filter_format',
        ),
      ),
      'indexes' => array(
        'format' => array(
          0 => 'format',
        ),
      ),
      'module' => 'text',
      'settings' => array(),
      'translatable' => '1',
      'type' => 'text_with_summary',
    ),
    'field_instance' => array(
      'bundle' => 'product_feature',
      'default_value' => array(
        0 => array(
          'format' => 'wysiwyg_editor',
          'summary' => 'Credibly revolutionize mission-critical niches vis-a-vis real-time relationships. Seamlessly cultivate accurate paradigms via state of the art mindshare. Appropriately target future-proof infrastructures without proactive e-markets. ',
          'value' => 'Credibly revolutionize mission-critical niches vis-a-vis real-time relationships. Seamlessly cultivate accurate paradigms via state of the art mindshare. Appropriately target future-proof infrastructures without proactive e-markets. Credibly maximize interdependent architectures for synergistic e-markets. Monotonectally create team building benefits via multimedia based sources. Dramatically supply end-to-end "outside the box" thinking vis-a-vis excellent processes. 

Credibly revolutionize mission-critical niches vis-a-vis real-time relationships. Seamlessly cultivate accurate paradigms via state of the art mindshare. Appropriately target future-proof infrastructures without proactive e-markets. Credibly maximize interdependent architectures for synergistic e-markets. Monotonectally create team building benefits via multimedia based sources. Dramatically supply end-to-end "outside the box" thinking vis-a-vis excellent processes. ',
        ),
      ),
      'deleted' => '0',
      'description' => 'Provide a full description for your feature',
      'display' => array(
        'default' => array(
          'label' => 'hidden',
          'module' => 'text',
          'settings' => array(),
          'type' => 'text_default',
          'weight' => '1',
        ),
        'teaser' => array(
          'label' => 'hidden',
          'module' => 'text',
          'settings' => array(
            'trim_length' => 600,
          ),
          'type' => 'text_summary_or_trimmed',
          'weight' => '1',
        ),
      ),
      'entity_type' => 'node',
      'field_name' => 'body',
      'label' => 'Feature Description',
      'required' => 0,
      'settings' => array(
        'display_summary' => 1,
        'text_processing' => '1',
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 1,
        'module' => 'text',
        'settings' => array(
          'rows' => '20',
          'summary_rows' => 5,
        ),
        'type' => 'text_textarea_with_summary',
        'weight' => '2',
      ),
    ),
  );

  // Exported field: 'node-product_feature-field_feature_benefit1'
  $fields['node-product_feature-field_feature_benefit1'] = array(
    'field_config' => array(
      'active' => '1',
      'cardinality' => '1',
      'deleted' => '0',
      'entity_types' => array(),
      'field_name' => 'field_feature_benefit1',
      'foreign keys' => array(
        'format' => array(
          'columns' => array(
            'format' => 'format',
          ),
          'table' => 'filter_format',
        ),
      ),
      'indexes' => array(
        'format' => array(
          0 => 'format',
        ),
      ),
      'module' => 'text',
      'settings' => array(),
      'translatable' => '0',
      'type' => 'text_long',
    ),
    'field_instance' => array(
      'bundle' => 'product_feature',
      'default_value' => array(
        0 => array(
          'value' => 'Appropriately maintain value-added sources and customized methods of empowerment. Conveniently plagiarize unique products via cross-unit schemas.',
        ),
      ),
      'deleted' => '0',
      'description' => 'Provide a clear description of the benefit this feature of your provides to your customer.
<i>Eg. This feature saves our customers time by allowing them to manage details in one place</i>',
      'display' => array(
        'default' => array(
          'label' => 'above',
          'module' => 'text',
          'settings' => array(),
          'type' => 'text_default',
          'weight' => '2',
        ),
        'teaser' => array(
          'label' => 'hidden',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => '3',
        ),
      ),
      'entity_type' => 'node',
      'field_name' => 'field_feature_benefit1',
      'label' => 'Customer Benefit',
      'required' => 0,
      'settings' => array(
        'text_processing' => '0',
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 1,
        'module' => 'text',
        'settings' => array(
          'rows' => '3',
        ),
        'type' => 'text_textarea',
        'weight' => '1',
      ),
    ),
  );

  // Exported field: 'node-product_feature-field_feature_icon'
  $fields['node-product_feature-field_feature_icon'] = array(
    'field_config' => array(
      'active' => '1',
      'cardinality' => '1',
      'deleted' => '0',
      'entity_types' => array(),
      'field_name' => 'field_feature_icon',
      'foreign keys' => array(
        'fid' => array(
          'columns' => array(
            'fid' => 'fid',
          ),
          'table' => 'file_managed',
        ),
      ),
      'indexes' => array(
        'fid' => array(
          0 => 'fid',
        ),
      ),
      'module' => 'image',
      'settings' => array(
        'default_image' => '1',
        'uri_scheme' => 'public',
      ),
      'translatable' => '0',
      'type' => 'image',
    ),
    'field_instance' => array(
      'bundle' => 'product_feature',
      'deleted' => '0',
      'description' => '',
      'display' => array(
        'default' => array(
          'label' => 'hidden',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => '3',
        ),
        'teaser' => array(
          'label' => 'hidden',
          'module' => 'image',
          'settings' => array(
            'image_link' => '',
            'image_style' => '',
          ),
          'type' => 'image',
          'weight' => '0',
        ),
      ),
      'entity_type' => 'node',
      'field_name' => 'field_feature_icon',
      'label' => 'Icon',
      'required' => 0,
      'settings' => array(
        'alt_field' => 1,
        'file_directory' => 'icons',
        'file_extensions' => 'png gif jpg jpeg',
        'max_filesize' => '',
        'max_resolution' => '',
        'min_resolution' => '',
        'title_field' => 0,
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 1,
        'module' => 'image',
        'settings' => array(
          'preview_image_style' => 'thumbnail',
          'progress_indicator' => 'throbber',
        ),
        'type' => 'image_image',
        'weight' => '3',
      ),
    ),
  );

  // Exported field: 'node-product_feature-field_feature_screenshots'
  $fields['node-product_feature-field_feature_screenshots'] = array(
    'field_config' => array(
      'active' => '1',
      'cardinality' => '3',
      'deleted' => '0',
      'entity_types' => array(),
      'field_name' => 'field_feature_screenshots',
      'foreign keys' => array(
        'fid' => array(
          'columns' => array(
            'fid' => 'fid',
          ),
          'table' => 'file_managed',
        ),
      ),
      'indexes' => array(
        'fid' => array(
          0 => 'fid',
        ),
      ),
      'module' => 'image',
      'settings' => array(
        'default_image' => 0,
        'uri_scheme' => 'public',
      ),
      'translatable' => '0',
      'type' => 'image',
    ),
    'field_instance' => array(
      'bundle' => 'product_feature',
      'deleted' => '0',
      'description' => '',
      'display' => array(
        'default' => array(
          'label' => 'hidden',
          'module' => 'image',
          'settings' => array(
            'image_link' => '',
            'image_style' => 'large',
          ),
          'type' => 'image',
          'weight' => '0',
        ),
        'teaser' => array(
          'label' => 'hidden',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => '2',
        ),
      ),
      'entity_type' => 'node',
      'field_name' => 'field_feature_screenshots',
      'label' => 'Screenshots',
      'required' => 0,
      'settings' => array(
        'alt_field' => 0,
        'file_directory' => '',
        'file_extensions' => 'png gif jpg jpeg',
        'max_filesize' => '',
        'max_resolution' => '2000x2000',
        'min_resolution' => '400x300',
        'title_field' => 0,
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 1,
        'module' => 'image',
        'settings' => array(
          'preview_image_style' => 'thumbnail',
          'progress_indicator' => 'throbber',
        ),
        'type' => 'image_image',
        'weight' => '4',
      ),
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('Customer Benefit');
  t('Feature Description');
  t('Icon');
  t('Provide a clear description of the benefit this feature of your provides to your customer.
<i>Eg. This feature saves our customers time by allowing them to manage details in one place</i>');
  t('Provide a full description for your feature');
  t('Screenshots');

  return $fields;
}
